<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/ZwiftPHP/ZwiftPHP.proto

namespace ZwiftPHP\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ZwiftPHP.Protobuf.EventSubgroupProtobuf</code>
 */
class EventSubgroupProtobuf extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>int32 rules = 8;</code>
     */
    private $rules = 0;
    /**
     * Generated from protobuf field <code>int32 route = 22;</code>
     */
    private $route = 0;
    /**
     * Generated from protobuf field <code>int32 laps = 25;</code>
     */
    private $laps = 0;
    /**
     * Generated from protobuf field <code>int32 startLocation = 29;</code>
     */
    private $startLocation = 0;
    /**
     * Generated from protobuf field <code>int32 label = 30;</code>
     */
    private $label = 0;
    /**
     * Generated from protobuf field <code>int32 paceType = 31;</code>
     */
    private $paceType = 0;
    /**
     * Generated from protobuf field <code>int32 jerseyHash = 36;</code>
     */
    private $jerseyHash = 0;

    public function __construct() {
        \GPBMetadata\Src\ZwiftPHP\ZwiftPHP::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rules = 8;</code>
     * @return int
     */
    public function getRules()
    {
        return $this->rules;
    }

    /**
     * Generated from protobuf field <code>int32 rules = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setRules($var)
    {
        GPBUtil::checkInt32($var);
        $this->rules = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 route = 22;</code>
     * @return int
     */
    public function getRoute()
    {
        return $this->route;
    }

    /**
     * Generated from protobuf field <code>int32 route = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setRoute($var)
    {
        GPBUtil::checkInt32($var);
        $this->route = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 laps = 25;</code>
     * @return int
     */
    public function getLaps()
    {
        return $this->laps;
    }

    /**
     * Generated from protobuf field <code>int32 laps = 25;</code>
     * @param int $var
     * @return $this
     */
    public function setLaps($var)
    {
        GPBUtil::checkInt32($var);
        $this->laps = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 startLocation = 29;</code>
     * @return int
     */
    public function getStartLocation()
    {
        return $this->startLocation;
    }

    /**
     * Generated from protobuf field <code>int32 startLocation = 29;</code>
     * @param int $var
     * @return $this
     */
    public function setStartLocation($var)
    {
        GPBUtil::checkInt32($var);
        $this->startLocation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 label = 30;</code>
     * @return int
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Generated from protobuf field <code>int32 label = 30;</code>
     * @param int $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkInt32($var);
        $this->label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 paceType = 31;</code>
     * @return int
     */
    public function getPaceType()
    {
        return $this->paceType;
    }

    /**
     * Generated from protobuf field <code>int32 paceType = 31;</code>
     * @param int $var
     * @return $this
     */
    public function setPaceType($var)
    {
        GPBUtil::checkInt32($var);
        $this->paceType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 jerseyHash = 36;</code>
     * @return int
     */
    public function getJerseyHash()
    {
        return $this->jerseyHash;
    }

    /**
     * Generated from protobuf field <code>int32 jerseyHash = 36;</code>
     * @param int $var
     * @return $this
     */
    public function setJerseyHash($var)
    {
        GPBUtil::checkInt32($var);
        $this->jerseyHash = $var;

        return $this;
    }

}

