<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/ZwiftPHP/ZwiftPHP.proto

namespace ZwiftPHP\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ZwiftPHP.Protobuf.PlayerState</code>
 */
class PlayerState extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>int64 worldTime = 2;</code>
     */
    private $worldTime = 0;
    /**
     * Generated from protobuf field <code>int32 distance = 3;</code>
     */
    private $distance = 0;
    /**
     * Generated from protobuf field <code>int32 roadTime = 4;</code>
     */
    private $roadTime = 0;
    /**
     * Generated from protobuf field <code>int32 laps = 5;</code>
     */
    private $laps = 0;
    /**
     * Generated from protobuf field <code>int32 speed = 6;</code>
     */
    private $speed = 0;
    /**
     * Generated from protobuf field <code>int32 roadPosition = 8;</code>
     */
    private $roadPosition = 0;
    /**
     * Generated from protobuf field <code>int32 cadenceUHz = 9;</code>
     */
    private $cadenceUHz = 0;
    /**
     * Generated from protobuf field <code>int32 heartrate = 11;</code>
     */
    private $heartrate = 0;
    /**
     * Generated from protobuf field <code>int32 power = 12;</code>
     */
    private $power = 0;
    /**
     * Generated from protobuf field <code>int64 heading = 13;</code>
     */
    private $heading = 0;
    /**
     * Generated from protobuf field <code>int32 lean = 14;</code>
     */
    private $lean = 0;
    /**
     * Generated from protobuf field <code>int32 climbing = 15;</code>
     */
    private $climbing = 0;
    /**
     * Generated from protobuf field <code>int32 time = 16;</code>
     */
    private $time = 0;
    /**
     * Generated from protobuf field <code>int32 f19 = 19;</code>
     */
    private $f19 = 0;
    /**
     * Generated from protobuf field <code>int32 f20 = 20;</code>
     */
    private $f20 = 0;
    /**
     * Generated from protobuf field <code>int32 progress = 21;</code>
     */
    private $progress = 0;
    /**
     * Generated from protobuf field <code>int64 customisationId = 22;</code>
     */
    private $customisationId = 0;
    /**
     * Generated from protobuf field <code>int32 justWatching = 23;</code>
     */
    private $justWatching = 0;
    /**
     * Generated from protobuf field <code>int32 calories = 24;</code>
     */
    private $calories = 0;
    /**
     * Generated from protobuf field <code>float x = 25;</code>
     */
    private $x = 0.0;
    /**
     * Generated from protobuf field <code>float altitude = 26;</code>
     */
    private $altitude = 0.0;
    /**
     * Generated from protobuf field <code>float y = 27;</code>
     */
    private $y = 0.0;
    /**
     * Generated from protobuf field <code>int32 watchingRiderId = 28;</code>
     */
    private $watchingRiderId = 0;
    /**
     * Generated from protobuf field <code>int32 groupId = 29;</code>
     */
    private $groupId = 0;
    /**
     * Generated from protobuf field <code>int64 sport = 31;</code>
     */
    private $sport = 0;

    public function __construct() {
        \GPBMetadata\Src\ZwiftPHP\ZwiftPHP::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 worldTime = 2;</code>
     * @return int|string
     */
    public function getWorldTime()
    {
        return $this->worldTime;
    }

    /**
     * Generated from protobuf field <code>int64 worldTime = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWorldTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->worldTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 distance = 3;</code>
     * @return int
     */
    public function getDistance()
    {
        return $this->distance;
    }

    /**
     * Generated from protobuf field <code>int32 distance = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDistance($var)
    {
        GPBUtil::checkInt32($var);
        $this->distance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 roadTime = 4;</code>
     * @return int
     */
    public function getRoadTime()
    {
        return $this->roadTime;
    }

    /**
     * Generated from protobuf field <code>int32 roadTime = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRoadTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->roadTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 laps = 5;</code>
     * @return int
     */
    public function getLaps()
    {
        return $this->laps;
    }

    /**
     * Generated from protobuf field <code>int32 laps = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setLaps($var)
    {
        GPBUtil::checkInt32($var);
        $this->laps = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 speed = 6;</code>
     * @return int
     */
    public function getSpeed()
    {
        return $this->speed;
    }

    /**
     * Generated from protobuf field <code>int32 speed = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSpeed($var)
    {
        GPBUtil::checkInt32($var);
        $this->speed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 roadPosition = 8;</code>
     * @return int
     */
    public function getRoadPosition()
    {
        return $this->roadPosition;
    }

    /**
     * Generated from protobuf field <code>int32 roadPosition = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setRoadPosition($var)
    {
        GPBUtil::checkInt32($var);
        $this->roadPosition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cadenceUHz = 9;</code>
     * @return int
     */
    public function getCadenceUHz()
    {
        return $this->cadenceUHz;
    }

    /**
     * Generated from protobuf field <code>int32 cadenceUHz = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setCadenceUHz($var)
    {
        GPBUtil::checkInt32($var);
        $this->cadenceUHz = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 heartrate = 11;</code>
     * @return int
     */
    public function getHeartrate()
    {
        return $this->heartrate;
    }

    /**
     * Generated from protobuf field <code>int32 heartrate = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setHeartrate($var)
    {
        GPBUtil::checkInt32($var);
        $this->heartrate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 power = 12;</code>
     * @return int
     */
    public function getPower()
    {
        return $this->power;
    }

    /**
     * Generated from protobuf field <code>int32 power = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setPower($var)
    {
        GPBUtil::checkInt32($var);
        $this->power = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 heading = 13;</code>
     * @return int|string
     */
    public function getHeading()
    {
        return $this->heading;
    }

    /**
     * Generated from protobuf field <code>int64 heading = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHeading($var)
    {
        GPBUtil::checkInt64($var);
        $this->heading = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 lean = 14;</code>
     * @return int
     */
    public function getLean()
    {
        return $this->lean;
    }

    /**
     * Generated from protobuf field <code>int32 lean = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setLean($var)
    {
        GPBUtil::checkInt32($var);
        $this->lean = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 climbing = 15;</code>
     * @return int
     */
    public function getClimbing()
    {
        return $this->climbing;
    }

    /**
     * Generated from protobuf field <code>int32 climbing = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setClimbing($var)
    {
        GPBUtil::checkInt32($var);
        $this->climbing = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 time = 16;</code>
     * @return int
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>int32 time = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 f19 = 19;</code>
     * @return int
     */
    public function getF19()
    {
        return $this->f19;
    }

    /**
     * Generated from protobuf field <code>int32 f19 = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setF19($var)
    {
        GPBUtil::checkInt32($var);
        $this->f19 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 f20 = 20;</code>
     * @return int
     */
    public function getF20()
    {
        return $this->f20;
    }

    /**
     * Generated from protobuf field <code>int32 f20 = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setF20($var)
    {
        GPBUtil::checkInt32($var);
        $this->f20 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 progress = 21;</code>
     * @return int
     */
    public function getProgress()
    {
        return $this->progress;
    }

    /**
     * Generated from protobuf field <code>int32 progress = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setProgress($var)
    {
        GPBUtil::checkInt32($var);
        $this->progress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 customisationId = 22;</code>
     * @return int|string
     */
    public function getCustomisationId()
    {
        return $this->customisationId;
    }

    /**
     * Generated from protobuf field <code>int64 customisationId = 22;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCustomisationId($var)
    {
        GPBUtil::checkInt64($var);
        $this->customisationId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 justWatching = 23;</code>
     * @return int
     */
    public function getJustWatching()
    {
        return $this->justWatching;
    }

    /**
     * Generated from protobuf field <code>int32 justWatching = 23;</code>
     * @param int $var
     * @return $this
     */
    public function setJustWatching($var)
    {
        GPBUtil::checkInt32($var);
        $this->justWatching = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 calories = 24;</code>
     * @return int
     */
    public function getCalories()
    {
        return $this->calories;
    }

    /**
     * Generated from protobuf field <code>int32 calories = 24;</code>
     * @param int $var
     * @return $this
     */
    public function setCalories($var)
    {
        GPBUtil::checkInt32($var);
        $this->calories = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float x = 25;</code>
     * @return float
     */
    public function getX()
    {
        return $this->x;
    }

    /**
     * Generated from protobuf field <code>float x = 25;</code>
     * @param float $var
     * @return $this
     */
    public function setX($var)
    {
        GPBUtil::checkFloat($var);
        $this->x = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float altitude = 26;</code>
     * @return float
     */
    public function getAltitude()
    {
        return $this->altitude;
    }

    /**
     * Generated from protobuf field <code>float altitude = 26;</code>
     * @param float $var
     * @return $this
     */
    public function setAltitude($var)
    {
        GPBUtil::checkFloat($var);
        $this->altitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float y = 27;</code>
     * @return float
     */
    public function getY()
    {
        return $this->y;
    }

    /**
     * Generated from protobuf field <code>float y = 27;</code>
     * @param float $var
     * @return $this
     */
    public function setY($var)
    {
        GPBUtil::checkFloat($var);
        $this->y = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 watchingRiderId = 28;</code>
     * @return int
     */
    public function getWatchingRiderId()
    {
        return $this->watchingRiderId;
    }

    /**
     * Generated from protobuf field <code>int32 watchingRiderId = 28;</code>
     * @param int $var
     * @return $this
     */
    public function setWatchingRiderId($var)
    {
        GPBUtil::checkInt32($var);
        $this->watchingRiderId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 groupId = 29;</code>
     * @return int
     */
    public function getGroupId()
    {
        return $this->groupId;
    }

    /**
     * Generated from protobuf field <code>int32 groupId = 29;</code>
     * @param int $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkInt32($var);
        $this->groupId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 sport = 31;</code>
     * @return int|string
     */
    public function getSport()
    {
        return $this->sport;
    }

    /**
     * Generated from protobuf field <code>int64 sport = 31;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSport($var)
    {
        GPBUtil::checkInt64($var);
        $this->sport = $var;

        return $this;
    }

}

