<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/ZwiftPHP/ZwiftPHP.proto

namespace ZwiftPHP\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ZwiftPHP.Protobuf.RiderAttributes.AttributeMessage</code>
 */
class RiderAttributes_AttributeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 myId = 1;</code>
     */
    private $myId = 0;
    /**
     * Generated from protobuf field <code>int32 theirId = 2;</code>
     */
    private $theirId = 0;
    /**
     * Generated from protobuf field <code>string firstName = 3;</code>
     */
    private $firstName = '';
    /**
     * Generated from protobuf field <code>string lastName = 4;</code>
     */
    private $lastName = '';
    /**
     * Generated from protobuf field <code>int32 countryCode = 5;</code>
     */
    private $countryCode = 0;

    public function __construct() {
        \GPBMetadata\Src\ZwiftPHP\ZwiftPHP::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 myId = 1;</code>
     * @return int
     */
    public function getMyId()
    {
        return $this->myId;
    }

    /**
     * Generated from protobuf field <code>int32 myId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMyId($var)
    {
        GPBUtil::checkInt32($var);
        $this->myId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 theirId = 2;</code>
     * @return int
     */
    public function getTheirId()
    {
        return $this->theirId;
    }

    /**
     * Generated from protobuf field <code>int32 theirId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTheirId($var)
    {
        GPBUtil::checkInt32($var);
        $this->theirId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string firstName = 3;</code>
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Generated from protobuf field <code>string firstName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->firstName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string lastName = 4;</code>
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Generated from protobuf field <code>string lastName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->lastName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 countryCode = 5;</code>
     * @return int
     */
    public function getCountryCode()
    {
        return $this->countryCode;
    }

    /**
     * Generated from protobuf field <code>int32 countryCode = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setCountryCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->countryCode = $var;

        return $this;
    }

}

