<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/ZwiftPHP/ZwiftPHP.proto

namespace ZwiftPHP\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ZwiftPHP.Protobuf.SegmentResult</code>
 */
class SegmentResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>int64 rider_id = 2;</code>
     */
    private $rider_id = 0;
    /**
     * Generated from protobuf field <code>int64 event_subgroup_id = 6;</code>
     */
    private $event_subgroup_id = 0;
    /**
     * Generated from protobuf field <code>string first_name = 7;</code>
     */
    private $first_name = '';
    /**
     * Generated from protobuf field <code>string last_name = 8;</code>
     */
    private $last_name = '';
    /**
     * Generated from protobuf field <code>string finish_time_str = 10;</code>
     */
    private $finish_time_str = '';
    /**
     * Generated from protobuf field <code>int64 elapsed_ms = 11;</code>
     */
    private $elapsed_ms = 0;
    /**
     * Generated from protobuf field <code>int32 powermeter = 12;</code>
     */
    private $powermeter = 0;
    /**
     * Generated from protobuf field <code>int32 weight = 13;</code>
     */
    private $weight = 0;
    /**
     * Generated from protobuf field <code>int32 power = 15;</code>
     */
    private $power = 0;
    /**
     * Generated from protobuf field <code>int32 heartrate = 19;</code>
     */
    private $heartrate = 0;

    public function __construct() {
        \GPBMetadata\Src\ZwiftPHP\ZwiftPHP::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 rider_id = 2;</code>
     * @return int|string
     */
    public function getRiderId()
    {
        return $this->rider_id;
    }

    /**
     * Generated from protobuf field <code>int64 rider_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRiderId($var)
    {
        GPBUtil::checkInt64($var);
        $this->rider_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 event_subgroup_id = 6;</code>
     * @return int|string
     */
    public function getEventSubgroupId()
    {
        return $this->event_subgroup_id;
    }

    /**
     * Generated from protobuf field <code>int64 event_subgroup_id = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEventSubgroupId($var)
    {
        GPBUtil::checkInt64($var);
        $this->event_subgroup_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string first_name = 7;</code>
     * @return string
     */
    public function getFirstName()
    {
        return $this->first_name;
    }

    /**
     * Generated from protobuf field <code>string first_name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->first_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_name = 8;</code>
     * @return string
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * Generated from protobuf field <code>string last_name = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string finish_time_str = 10;</code>
     * @return string
     */
    public function getFinishTimeStr()
    {
        return $this->finish_time_str;
    }

    /**
     * Generated from protobuf field <code>string finish_time_str = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setFinishTimeStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->finish_time_str = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 elapsed_ms = 11;</code>
     * @return int|string
     */
    public function getElapsedMs()
    {
        return $this->elapsed_ms;
    }

    /**
     * Generated from protobuf field <code>int64 elapsed_ms = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setElapsedMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->elapsed_ms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 powermeter = 12;</code>
     * @return int
     */
    public function getPowermeter()
    {
        return $this->powermeter;
    }

    /**
     * Generated from protobuf field <code>int32 powermeter = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setPowermeter($var)
    {
        GPBUtil::checkInt32($var);
        $this->powermeter = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 weight = 13;</code>
     * @return int
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Generated from protobuf field <code>int32 weight = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->weight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 power = 15;</code>
     * @return int
     */
    public function getPower()
    {
        return $this->power;
    }

    /**
     * Generated from protobuf field <code>int32 power = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setPower($var)
    {
        GPBUtil::checkInt32($var);
        $this->power = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 heartrate = 19;</code>
     * @return int
     */
    public function getHeartrate()
    {
        return $this->heartrate;
    }

    /**
     * Generated from protobuf field <code>int32 heartrate = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setHeartrate($var)
    {
        GPBUtil::checkInt32($var);
        $this->heartrate = $var;

        return $this;
    }

}

