<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/ZwiftPHP/ZwiftPHP.proto

namespace ZwiftPHP\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ZwiftPHP.Protobuf.SegmentResults</code>
 */
class SegmentResults extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 world_id = 1;</code>
     */
    private $world_id = 0;
    /**
     * Generated from protobuf field <code>int64 segment_id = 2;</code>
     */
    private $segment_id = 0;
    /**
     * Generated from protobuf field <code>int64 event_subgroup_id = 3;</code>
     */
    private $event_subgroup_id = 0;
    /**
     * Generated from protobuf field <code>repeated .ZwiftPHP.Protobuf.SegmentResult segment_results = 4;</code>
     */
    private $segment_results;

    public function __construct() {
        \GPBMetadata\Src\ZwiftPHP\ZwiftPHP::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 world_id = 1;</code>
     * @return int|string
     */
    public function getWorldId()
    {
        return $this->world_id;
    }

    /**
     * Generated from protobuf field <code>int64 world_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWorldId($var)
    {
        GPBUtil::checkInt64($var);
        $this->world_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 segment_id = 2;</code>
     * @return int|string
     */
    public function getSegmentId()
    {
        return $this->segment_id;
    }

    /**
     * Generated from protobuf field <code>int64 segment_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSegmentId($var)
    {
        GPBUtil::checkInt64($var);
        $this->segment_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 event_subgroup_id = 3;</code>
     * @return int|string
     */
    public function getEventSubgroupId()
    {
        return $this->event_subgroup_id;
    }

    /**
     * Generated from protobuf field <code>int64 event_subgroup_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEventSubgroupId($var)
    {
        GPBUtil::checkInt64($var);
        $this->event_subgroup_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ZwiftPHP.Protobuf.SegmentResult segment_results = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSegmentResults()
    {
        return $this->segment_results;
    }

    /**
     * Generated from protobuf field <code>repeated .ZwiftPHP.Protobuf.SegmentResult segment_results = 4;</code>
     * @param \ZwiftPHP\Protobuf\SegmentResult[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSegmentResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ZwiftPHP\Protobuf\SegmentResult::class);
        $this->segment_results = $arr;

        return $this;
    }

}

