<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/ZwiftPHP/ZwiftPHP.proto

namespace ZwiftPHP\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ZwiftPHP.Protobuf.ServerToClient</code>
 */
class ServerToClient extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 tag1 = 1;</code>
     */
    private $tag1 = 0;
    /**
     * Generated from protobuf field <code>int32 rider_id = 2;</code>
     */
    private $rider_id = 0;
    /**
     * Generated from protobuf field <code>int64 world_time = 3;</code>
     */
    private $world_time = 0;
    /**
     * Generated from protobuf field <code>int32 seqno = 4;</code>
     */
    private $seqno = 0;
    /**
     * Generated from protobuf field <code>repeated .ZwiftPHP.Protobuf.PlayerState player_states = 8;</code>
     */
    private $player_states;
    /**
     * Generated from protobuf field <code>repeated .ZwiftPHP.Protobuf.UnknownMessage player_updates = 9;</code>
     */
    private $player_updates;
    /**
     * Generated from protobuf field <code>int64 tag11 = 11;</code>
     */
    private $tag11 = 0;
    /**
     * Generated from protobuf field <code>int64 tag17 = 17;</code>
     */
    private $tag17 = 0;
    /**
     * Generated from protobuf field <code>int32 num_msgs = 18;</code>
     */
    private $num_msgs = 0;
    /**
     * Generated from protobuf field <code>int32 msgnum = 19;</code>
     */
    private $msgnum = 0;

    public function __construct() {
        \GPBMetadata\Src\ZwiftPHP\ZwiftPHP::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 tag1 = 1;</code>
     * @return int
     */
    public function getTag1()
    {
        return $this->tag1;
    }

    /**
     * Generated from protobuf field <code>int32 tag1 = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTag1($var)
    {
        GPBUtil::checkInt32($var);
        $this->tag1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rider_id = 2;</code>
     * @return int
     */
    public function getRiderId()
    {
        return $this->rider_id;
    }

    /**
     * Generated from protobuf field <code>int32 rider_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRiderId($var)
    {
        GPBUtil::checkInt32($var);
        $this->rider_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 world_time = 3;</code>
     * @return int|string
     */
    public function getWorldTime()
    {
        return $this->world_time;
    }

    /**
     * Generated from protobuf field <code>int64 world_time = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWorldTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->world_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 seqno = 4;</code>
     * @return int
     */
    public function getSeqno()
    {
        return $this->seqno;
    }

    /**
     * Generated from protobuf field <code>int32 seqno = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSeqno($var)
    {
        GPBUtil::checkInt32($var);
        $this->seqno = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ZwiftPHP.Protobuf.PlayerState player_states = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPlayerStates()
    {
        return $this->player_states;
    }

    /**
     * Generated from protobuf field <code>repeated .ZwiftPHP.Protobuf.PlayerState player_states = 8;</code>
     * @param \ZwiftPHP\Protobuf\PlayerState[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPlayerStates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ZwiftPHP\Protobuf\PlayerState::class);
        $this->player_states = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ZwiftPHP.Protobuf.UnknownMessage player_updates = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPlayerUpdates()
    {
        return $this->player_updates;
    }

    /**
     * Generated from protobuf field <code>repeated .ZwiftPHP.Protobuf.UnknownMessage player_updates = 9;</code>
     * @param \ZwiftPHP\Protobuf\UnknownMessage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPlayerUpdates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ZwiftPHP\Protobuf\UnknownMessage::class);
        $this->player_updates = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 tag11 = 11;</code>
     * @return int|string
     */
    public function getTag11()
    {
        return $this->tag11;
    }

    /**
     * Generated from protobuf field <code>int64 tag11 = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTag11($var)
    {
        GPBUtil::checkInt64($var);
        $this->tag11 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 tag17 = 17;</code>
     * @return int|string
     */
    public function getTag17()
    {
        return $this->tag17;
    }

    /**
     * Generated from protobuf field <code>int64 tag17 = 17;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTag17($var)
    {
        GPBUtil::checkInt64($var);
        $this->tag17 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 num_msgs = 18;</code>
     * @return int
     */
    public function getNumMsgs()
    {
        return $this->num_msgs;
    }

    /**
     * Generated from protobuf field <code>int32 num_msgs = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setNumMsgs($var)
    {
        GPBUtil::checkInt32($var);
        $this->num_msgs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 msgnum = 19;</code>
     * @return int
     */
    public function getMsgnum()
    {
        return $this->msgnum;
    }

    /**
     * Generated from protobuf field <code>int32 msgnum = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgnum($var)
    {
        GPBUtil::checkInt32($var);
        $this->msgnum = $var;

        return $this;
    }

}

