<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/ZwiftPHP/ZwiftPHP.proto

namespace ZwiftPHP\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * int64 tag1=1;
 * UnknownMessage1 tag4=4;
 *
 * Generated from protobuf message <code>ZwiftPHP.Protobuf.UnknownMessage</code>
 */
class UnknownMessage extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Src\ZwiftPHP\ZwiftPHP::initOnce();
        parent::__construct();
    }

}

