<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/ZwiftPHP/ZwiftPHP.proto

namespace ZwiftPHP\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * string firstName=7;
 * string lastName=8;
 * string timestamp=17;
 *
 * Generated from protobuf message <code>ZwiftPHP.Protobuf.UnknownMessage1</code>
 */
class UnknownMessage1 extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Src\ZwiftPHP\ZwiftPHP::initOnce();
        parent::__construct();
    }

}

