<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/ZwiftPHP/ZwiftPHP.proto

namespace ZwiftPHP\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ZwiftPHP.Protobuf.WorldAttributes</code>
 */
class WorldAttributes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 world_id = 1;</code>
     */
    private $world_id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>int64 tag3 = 3;</code>
     */
    private $tag3 = 0;
    /**
     * Generated from protobuf field <code>int64 tag5 = 4;</code>
     */
    private $tag5 = 0;
    /**
     * Generated from protobuf field <code>int64 world_time = 6;</code>
     */
    private $world_time = 0;
    /**
     * Generated from protobuf field <code>int64 clock_time = 7;</code>
     */
    private $clock_time = 0;

    public function __construct() {
        \GPBMetadata\Src\ZwiftPHP\ZwiftPHP::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 world_id = 1;</code>
     * @return int
     */
    public function getWorldId()
    {
        return $this->world_id;
    }

    /**
     * Generated from protobuf field <code>int32 world_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setWorldId($var)
    {
        GPBUtil::checkInt32($var);
        $this->world_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 tag3 = 3;</code>
     * @return int|string
     */
    public function getTag3()
    {
        return $this->tag3;
    }

    /**
     * Generated from protobuf field <code>int64 tag3 = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTag3($var)
    {
        GPBUtil::checkInt64($var);
        $this->tag3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 tag5 = 4;</code>
     * @return int|string
     */
    public function getTag5()
    {
        return $this->tag5;
    }

    /**
     * Generated from protobuf field <code>int64 tag5 = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTag5($var)
    {
        GPBUtil::checkInt64($var);
        $this->tag5 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 world_time = 6;</code>
     * @return int|string
     */
    public function getWorldTime()
    {
        return $this->world_time;
    }

    /**
     * Generated from protobuf field <code>int64 world_time = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWorldTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->world_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 clock_time = 7;</code>
     * @return int|string
     */
    public function getClockTime()
    {
        return $this->clock_time;
    }

    /**
     * Generated from protobuf field <code>int64 clock_time = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClockTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->clock_time = $var;

        return $this;
    }

}

