<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/ZwiftPHP/ZwiftPHP.proto

namespace ZwiftPHP\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ZwiftPHP.Protobuf.WorldAttribute</code>
 */
class WorldAttribute extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 world_time = 2;</code>
     */
    private $world_time = 0;

    public function __construct() {
        \GPBMetadata\Src\ZwiftPHP\ZwiftPHP::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 world_time = 2;</code>
     * @return int|string
     */
    public function getWorldTime()
    {
        return $this->world_time;
    }

    /**
     * Generated from protobuf field <code>int64 world_time = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWorldTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->world_time = $var;

        return $this;
    }

}

